name: phatfluttergui
description: PHAT (Password Hashing Algorithm Tool) Calculator programmed in Flutter

#  The purpose of this tool is to let an individual enter text and have a hashed
#  output to use as the password to the site or program. Initially the program
#  will hash the input in SHA 256 and output in hexadecimal. The plans for this
#  program are to allow the selection of three different SHA lengths (256, 384,
#  and 512). Also, the output numbering system will be selectable between
#  hexadecimal, base64, and base58. Also, the number of digits in the ouput
#  will be selectable in case a site can only have a certain number of digits
#  in a password. THe last step will be for the output to be copied to the
#  clipboard so if can be pasted into the program or site.
#
# version 1.0.0: initial release
# version 1.0.1: Updated to have main window scrollable and programmed for 720p phone
#    instead of a 1080p phone for more compatibility with phones.

version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  fast_base58: ^0.1.8
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OverpassMono
       fonts:
        - asset: fonts/OverpassMono-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
